automotive-dlt.pc.in

The install destination might be lib64, and a CMake variable
exists that contains this information, CMAKE_INSTALL_LIBDIR.

pkg-config: fix library directory.

---

INSTALL

I've faced with cmake error while generating make files for dlt-daemon.
After searching a bit, I've found out that zlib and dbus packages needed to be installed for default dlt-daemon configuration.
I used Ubuntu 16.04 for build and after I installed the packages cmake generated project successfully.
I think that is good idea to mention required packages in INSTALL notes in order to save the time of someone who will try to build dlt-daemon as I did.

- Added missing build steps to INSTALL

---

src/daemon/dlt_daemon_client.c

Check if size of control request structure fits into actual payload datasize. In case it does not fit, return with error message.

daemon: check payload length before cast to struct

---

src/daemon/dlt_daemon_client.c
src/daemon/dlt_daemon_connection.c
src/daemon/dlt_daemon_connection_types.h
src/daemon/dlt_daemon_event_handler.c
src/daemon/dlt_daemon_event_handler.h

If connection to e.g. DLT Viewer is established/removed very frequently, a memory violation might happen due to a bug in connection handling.

Daemon connection handling fixes

---

CMakeLists.txt
src/lib/dlt_user.c

When the user library receives a log with log level DLT_LOG_FATAL it
triggers a segmentation fault to provide information to the developer
via tools like coredump.
This is meant to be used during development only and disabled per default.

CMake Option: Trigger segmentation fault in case of FATAL log

---

include/dlt/dlt_client.h
src/console/dlt-control-common.c
src/console/dlt-control.c
src/console/dlt-receive.c
src/gateway/dlt_gateway.c
src/lib/dlt_client.c
src/tests/dlt-test-client.c
src/tests/dlt-test-multi-process-client.c
src/tests/dlt-test-stress-client.c

Setter function introduced for seting up string parameters which are free'd in dlt_client_cleanup
dlt-receives crashes in case of it is running when daemon is stopped, because in dlt_client_cleanup because of a unnecessary free. Gateway and dlt-receive code is aligned now. 

dlt-client: fix dlt_client_cleanup memory handling

---

src/system/dlt-system.conf

Added additional information about how to enable syslog feature properly.
If still facing issue while capturing syslogs through client (e.g. dlt_viewer) after following given steps then install listed packages:
build-essential 
build-essential checkinstall
pkg-config libsystemd-journal-dev
Note:
It's is a known issue when you try to capture syslog via dlt_viewer then syslogs wouldn't come in dlt_viewer because of improper configuration (won't route the log to port 47111) of dlt-system.
Signed-off-by: Amber Bhardwaj <amber.bhardwaj10@gmail.com>

Added Description in dlt-system.conf

---

src/adaptor/dlt-adaptor-stdin.c
src/adaptor/dlt-adaptor-udp.c

dlt-adaptor-udp, dlt-adaptor-stdin: implement get of verbosity level from input, defaulting to INFO when
wrong type or none is provided
Signed-off-by: Gianfranco Costamagna <gianfranco.costamagna@abinsula.com>

dlt-adaptor-udp, dlt-adaptor-stdin: implement get of verbosity level from input

---

src/daemon/dlt_daemon_connection_types.h

dlt-daemon/src/daemon/dlt_daemon_event_handler.c: In function ‘dlt_daemon_handle_event’:
dlt-daemon/src/daemon/dlt_daemon_event_handler.c:131:30: waring: cast from pointer to integer of different size [-Wpointer-to-int-cast]
DltConnectionId id = (DltConnectionId)ev->data.ptr;
^
dlt-daemon/src/daemon/dlt_daemon_event_handler.c: In function ‘dlt_connection_check_activate’:
dlt-daemon/src/daemon/dlt_daemon_event_handler.c:381:27: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
ev.data.ptr = (void *)con->id;
^
Signed-off-by: Gordan Markuš <gordan.markus@pelagicore.com>

dlt_daemon_connection_types: fix build warnings

---

src/system/dlt-system-process-handling.c

In function ‘daemonize’:
dlt-daemon/src/system/dlt-system-process-handling.c:84:5: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
for(i = getdtablesize(); i >= 0; i--)
^~~
dlt-daemon/src/system/dlt-system-process-handling.c:87:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘for’
int fd = open("/dev/null",O_RDWR);
^~~
Singed-off-by: Gordan Markuš <gordan.markus@pelagicore.com>

dlt-system-process-handling: fix warning

---

doc/CMakeLists.txt

As discussed in the mailing list ( http://lists.genivi.org/pipermail/genivi-diagnostic-log-and-trace/2017-May/000492.html ), current compilation with WITH_DOC=ON is broken due to commit a961dba.
This pull request fixes it.
Please let me know if you prefer just receiving patches in the mailing list instead.
Signed-off-by: Pierre N <pierreN@users.noreply.github.com>

commit a961dba removed README which was necessary to generate asciidocs. Tell cmake to use README.md instead of README

---

src/daemon/CMakeLists.txt

By enabling the WITH_SYSTEMD and WITH_DLT_UNIT_TESTS cmake flags
the build will fail with an error due to a linking issue:
../src/daemon/libdlt_daemon.so: undefined reference to `sd_booted'
collect2: error: ld returned 1 exit status
Signed-off-by: Gordan Markuš <gordan.markus@pelagicore.com>

cmake: fix unit tests compilation with systemd

---

tests/start_systemd_journal_test.sh

Users in the 'systemd-journal' group can see all journalctl messages.
Usually the user is not found in that group and the
"start_systemd_journal_test.sh" script might hang because of this.
Starting  "dlt-system" with sudo privileges will mitigate this risk.
Signed-off-by: Gordan Markuš <gordan.markus@pelagicore.com>

journald adaptor: test with sudo privileges

---

src/offlinelogstorage/dlt_offline_logstorage_behavior.c

… in dlt_logstorage_open_log_file.
When using dlt-logstorage-ctrl utility, dlt_logstorage_open_log_file function calls sprintf with raw input (dlt-logstorage-ctrl -p argument) into a buffer on the stack (of size 50).
When the argument length is longer than 50, a buffer overflow happens.
I guess this could hypothetically create a small security issue if the user can choose himself the storage mount point path (depends of DLT usage).
This PR simply uses snprintf instead of sprintf and return an error if the stack variable is not big enough.
Signed-off-by: Pierre N <pierreN@users.noreply.github.com>

Prevent buffer overflow for mount point path

---

include/dlt/dlt_user.h

The dlt_user_log_write_start* function description mention the verbose/non-verbose option.
According to my understanding verbose means that the code contains the verbose version of message (message as full string).
The non-verbose version uses identifiers in order to reduce the message content and the interpretation of ids will be done by the viewer.
Therefore the comments should be modified to capture this correctly.

Fix verbose comment in dlt_user.h

---

.gitignore
src/daemon/dlt-daemon.c
src/daemon/dlt_daemon_common.c

- When dlt_daemon_user_send_log_level() called in
dlt_daemon_process_user_message_register_context() fails -1 was returned
which caused dlt_daemon_process_user_messages() to stop processing
receiver buffer. Remaining data was stuck until new data arrived over
FIFO.
- Make debug output of dlt_daemon_user_send_log_level() more
verbose.
Signed-off-by: Lutz Helwing <lutz_helwing@mentor.com>

Data stuck in receiver buffer when dlt_daemon_user_send_log_level() fails

---

src/daemon/dlt-daemon_cfg.h
src/daemon/dlt_daemon_connection.c
src/daemon/dlt_daemon_socket.c
src/daemon/dlt_daemon_socket.h

This patch prevents occasional corrupt messages, which occur mostly in situations, where system is highly utilized: e.g. socket send buffer is full (or situation when write function is interrupted).

Prevention for occasional corrupted messages 

---

src/daemon/dlt_daemon_client.c

Even Forcing log level and trace status of context to not exceed "ContextLogLevel" and "ContextTraceStatus" in dlt.conf file with ForceContextLogLevelAndTraceStatus = 1, the default log level is being overwritten with high value than expected by client(DLT_Viewer when default trace data request is sent ) and by dlt-control application on usage of (dlt-control -d loglevel IP_ADDRESS)
With provided patch/changes in place, when ForceContextLogLevelAndTraceStatus  is enabled the requested log level is checked with ContextLogLevel and if it satisfied the daemon default loglevel gets updated.

Update in dlt_daemon_client.c

---

src/console/dlt-control.c

Default trace status could not be set by "-f" option.

dlt-control: Fix Setting default trace status issue

---

src/daemon/dlt-daemon.c

Marker message had been continued to output
if application called dlt_log_marker() due to missing
byte removing processing against marker message.
Therefore the byte removing for marker message processing is added.

dlt-daemon: Fix repeated output of marker message

---

src/daemon/dlt_daemon_client.c

dlt-daemon entered to infinite loop when set log level request with
wildcards came from dlt-control due to variable size.

dlt-daemon: Fix infinite loop on set log level using wildcards

---

src/daemon/dlt_daemon_common.c

Change log level of several logs from WARNING to INFO.
1. User FIFO cannot be opened because the FIFO does not exist
--> This case can happen if DLT user app is one-shot
2. Runtime configuration file (dlt-runtime-application.cfg / dlt-runtime-context.cfg)
cannot be opened
--> This case can happen in normal use case.

dlt-daemon: Lower log level of logs not to output unintentional warning

---

include/dlt/dlt_client.h
include/dlt/dlt_protocol.h
src/console/dlt-control.c
src/daemon/dlt_daemon_client.c
src/daemon/dlt_daemon_client.h
src/daemon/dlt_daemon_common.c
src/daemon/dlt_daemon_common.h
src/lib/dlt_client.c

1. support for setting trace status using wildcards for both app and context
2. support for setting entire system trace status
*This Logic is as same as for changing log level.
(SHA: a966393
dlt-control: Provision to control entire system log level)
And also small bug fix for controlling entire log level & trace status is included in this pull request.

Introduce controlling entire system trace status feature from dlt-control

---

src/daemon/dlt-daemon.c

This patch changes Context un-/registration message not to output DLT
by default for the purpose of reducing trace messages.
Actually dlt-daemon already sends almost same meaning control message
which can show Context un-/registration([get_log_info] and [unregister_context]).
These are duplicate message and should be suppressed in normal case.
Only if "Verbose = 1" is set in dlt.conf, the messages are output as same as before.

dlt-daemon: Not output Context un-/registration DLT message by default

---

src/daemon/dlt-daemon.c
src/daemon/dlt_daemon_common.c

If application tries to send application registration request before
dlt-daemon startup, the request is sent twice as below:
1. Buffered request in user library buffer
2. New request when user app succeeds to attach to dlt-daemon
In previous, dlt-daemon had been output the registration messages
2 times even though these messages were come from same application.
This duplicated output is avoided by this change.
Warning message in case of dlt-runtime-context.cfg exists
is also avoided. This file is created when Control message: "Store Config"
is used. This is not irregular case.

dlt-daemon: Avoid to output duplicated application registration message

---

src/daemon/dlt-daemon.c

Error log in case of accept() failure is improved with errno info.
This helps us to analyze dlt-daemon's issue in future.
(e.g.)
Connection request come to wrong socket unexpectedly and this
causes exiting dlt-daemon.

dlt-daemon: Improve error logging on accept() failure

---

src/daemon/dlt_daemon_event_handler.c

When epoll detected error for TCP client connection, no state transition
had been happened. (Only the file descriptor had been closed)
To prevent this, dedicated close function is called according to connection type.

dlt-daemon: Fix no state transition to BUFFER state

---

src/daemon/dlt_daemon_event_handler.c

Issue:
Dlt-daemon sometimes crashes due to incorrect connection removal.
The dlt_daemon_remove_connection function does not remove an item from the linked list, it just frees the memory used by the list item. This item is still used by daemon.
Fix:
Added correct removing of linked-list element.

dlt-daemon: fixed linked-list element remove

---

src/console/dlt-control-common.c
src/console/logstorage/dlt-logstorage-common.c
systemd/3rdparty/sd-daemon.c

This PR is providing 3 fixes that allow us to build dlt-daemon with GCC 8 when the stringop-truncation warning is treated as an error.

Fix gcc 8 build

---

README.md
automotive-dlt.spec.in
doc/CMakeLists.txt
doc/dlt-sortbytimestamp.1
doc/dlt-sortbytimestamp.1.txt
doc/dlt_book.txt
doc/dlt_design_specification.txt
doc/dlt_user_manual.txt
src/console/CMakeLists.txt
src/console/dlt-sortbytimestamp.c

Add a commandline utility to sort a DLT file by timestamp.
By default a DLT file's messages are in the order they were
received by the logger. This is not ideal for tracing problems on
systems with multi-threaded programmes running on multi-core CPUs
since message reception order will not always (or even often)
correspond to message creation order.
The documentation deals with how to handle the problem case of DLT
files containing messages from multiple boot cycles.

Add dlt-sortbytimestamp utility plus documentation

---

src/shared/dlt_common.c

Hi there!
We're spawning dlt-daemon within an application piping stdout/err/in and waiting for certain output (for testing) but it blocks because by default pipes are buffered. It'd be nice to see the logs right away.

Fflush stdout in the intenal logger

---

include/dlt/dlt_client.h
include/dlt/dlt_common.h
include/dlt/dlt_protocol.h
src/console/dlt-control-common.c
src/console/dlt-control.c
src/console/dlt-receive.c
src/daemon/CMakeLists.txt
src/daemon/dlt_daemon_client.c
src/daemon/dlt_daemon_offline_logstorage.c
src/gateway/dlt_gateway.c
src/gateway/dlt_gateway.conf
src/gateway/dlt_gateway.h
src/gateway/dlt_gateway_types.h
src/lib/CMakeLists.txt
src/lib/dlt_client.c
src/lib/dlt_client_cfg.h
src/shared/dlt_common.c
src/shared/dlt_protocol.c
tests/dlt_test_receiver.c
tests/g_test_dlt_daemon_gateway.sh
tests/gtest_common.h
tests/gtest_dlt_daemon_event_handler.cpp
tests/gtest_dlt_daemon_gateway.cpp
tests/gtest_dlt_daemon_offline_log.cpp

-Support to send and parse periodic control messages
-add application/contexts to passive ECU list
-Refactor dlt_gateway_send_control_message
-Gateway issues with corrupted data and on demand connection
-DLT Service ID Enum instead of defines
-dlt-control: update get log info
-dlt-client: logging: Extended the receiver buffer size
-Unit Test update
Signed-off-by: S. Hameed <shameed@jp.adit-jv.com>
Signed-off-by: ManikandanC <Manikandan.Chockalingam@in.bosch.com>

Gateway Improvements

---

include/dlt/dlt_common.h
include/dlt/dlt_user.h
include/dlt/dlt_user_macros.h
src/adaptor/dlt-adaptor-stdin.c
src/console/dlt-receive.c
src/console/logstorage/CMakeLists.txt
src/console/logstorage/dlt-logstorage-ctrl.c
src/console/logstorage/dlt-logstorage-list.c
src/daemon/CMakeLists.txt
src/daemon/dlt-daemon.c
src/daemon/dlt_daemon_connection.c
src/daemon/dlt_daemon_connection_types.h
src/daemon/dlt_daemon_event_handler.c
src/daemon/dlt_daemon_event_handler.h
src/daemon/dlt_daemon_event_handler_types.h
src/gateway/dlt_gateway.c
src/gateway/dlt_gateway.h
src/lib/CMakeLists.txt
src/lib/dlt_user.c
src/shared/dlt_common.c
src/tests/dlt-test-multi-process.c
tests/gtest_dlt_daemon_event_handler.cpp

The poll system call is now used in the daemon to enable DLT use in
POSIX compliant systems. Also added introduced new unregister_app macro
to avoid missing of logs in startup buffer.
Signed-off-by: Frederic Berat <fberat@de.adit-jv.com>
Signed-off-by: ManikandanC <Manikandan.Chockalingam@in.bosch.com>
Signed-off-by: S. Hameed <shameed@jp.adit-jv.com>

Use poll in the dlt-daemon for POSIX compliance

---

src/daemon/dlt-daemon.c

In previous, number of connections was output only if verbose mode
in dlt.conf was enabled. This information is basically useful
and is not output frequently. Therefore number of connections information
is made to output as default when new connection is established or
the connection is lost.

dlt-daemon: Output current number of connections as default

---

src/daemon/dlt_daemon_offline_logstorage.c
src/offlinelogstorage/dlt_offline_logstorage.c
src/offlinelogstorage/dlt_offline_logstorage.h
src/offlinelogstorage/dlt_offline_logstorage_internal.h
tests/gtest_dlt_daemon_offline_log.cpp

Rootcause:
The dlt-daemon rotates files for each key, but not for each [FILTER] because
dlt-daemon creates the DltLogStorageFilterConfig for each key (CTXT: or APPID: or APPID:CTXTID)
then added to the DltLogStorageFilterList.
And each DltLogStorageFilterConfig has it's own records (The list of files
that was recorded in the offline logstorage directory), that's why one [FILTER] might be
has multiple records and then its lead to the problem.
Solution:
Instead of creating the DltLogStorageFilterConfig for each key, dlt-daemon will create
the DltLogStorageFilterConfig for each [FILTER] and DltLogStorageFilterConfig has an information
of all the keys in this [FILTER].

dlt_offline_logstorage: fix multiple file creation error (#85, #94)

---

include/dlt/dlt_types.h
src/lib/dlt_user.c

0xFFFF was used as a magic number in the length field of a network
message in order to trigger a resend. DLT library will now use the
nw_trace_type field and a custom type to do this, thus assuring no
external client of the library can reach this
value(DLT_NW_TRACE_USER_DEFINED7).

Fixed memory leak when receiving network traces of 0xFFFF length

---

systemd/CMakeLists.txt

Noticed that dlt-system.service unconditionally failed since the binary was missing when building with a default configuration after an upgrade from 2.17.0 to 2.18.1. WITH_DLT_SYSTEM default changed to OFF in 1b3c8b3d10fbc9a8dd9c717a939babd901b0b243 .
Fix by only installing dlt-system.service if dlt-system is built. Also do the same for other binaries that have a service file.

Do not install systemd service files for binaries that are not built

---

tests/gtest_dlt_daemon_gateway.cpp
tests/gtest_dlt_daemon_offline_log.cpp

- Initialize variables in gtest_dlt_daemon_gateway.cpp to avoid unexpected error.
- Support FIFO mode in connectServer() in gtest_dlt_daemon_logstorage.cpp.
Signed-off-by: Bui Nguyen Quoc Thanh <thanh.buinguyenquoc@vn.bosch.com>

Unit test fix

---

src/console/dlt-control.c
src/console/dlt-convert.c
src/console/logstorage/dlt-logstorage-ctrl.c
src/offlinelogstorage/dlt_offline_logstorage_behavior.c
src/shared/dlt_config_file_parser.c
src/shared/dlt_offline_trace.c

mirror change for clang compiler warnings.
```console
$ mkdir build
$ cd build
$ cmake -DCMAKE_C_COMPILER=clang-8 -DCMAKE_CXX_COMPILER=clang++-8 -DCMAKE_BUILD_TYPE=Debug -DWITH_DLT_TESTS=ON -DWITH_TESTSCRIPTS=ON -DWITH_DLT_UNIT_TESTS=ON -DWITH_SYSTEMD=ON -DWITH_SYSTEMD_JOURNAL=ON ..
$ make
```
gtest_dlt_* are fine.

Fix clang warning

---

CMakeLists.txt
include/dlt/CMakeLists.txt
src/console/CMakeLists.txt
src/daemon/CMakeLists.txt
src/lib/CMakeLists.txt
src/tests/CMakeLists.txt
tests/CMakeLists.txt

1. Allow building as a subproject of another
cmake project (CMAKE_* vs PROJECT_* variables)
2. Do not generate header files within source – bad practice, use build
directory for that(e.g. change location where dlt_version.h is being generated)
3. Use add_compile_options() instead of *_C/CXX_FLAGS variables for proper
compile environment definition, also bad practice, also see p.2
4. Add WITH_DLT_PKGCONFIG – add generate pkgconfig .pc files as switchable
option, should probably be part of headers install routine.
Signed-off-by: Radoslaw Kaczorowski <external.radoslaw.kaczorowski@bosch-softtec.com>

cmake-improvements

---

include/dlt/dlt_common.h
src/daemon/dlt-daemon.c
src/daemon/dlt-daemon.h
src/dbus/dlt-dbus-options.c
src/dbus/dlt-dbus.h
src/lib/dlt_user.c
src/offlinelogstorage/dlt_offline_logstorage.c
src/shared/dlt_common.c
src/shared/dlt_offline_trace.c

define DLT_PATH_MAX for max path buffer length
DLT limits the path length and does not do anything else to determine
the actual value, because the least that is supported on any system
that DLT runs on is 1024 bytes.

define DLT_PATH_MAX for max path buffer length

---

src/console/logstorage/dlt-logstorage-common.c

Mount path unitialized and it is always NULL inside the statement.
Signed-off-by: jiripopek <Jiri.Popek@bmw.de>

logstorage: fix compile error

---

src/system/dlt-system-journal.c

fixes compiler error
"error: too many arguments to function ‘localtime’"
Signed-off-by: jiripopek <Jiri.Popek@bmw.de>

dlt-system-journal: fixed localtime compile error

---

src/daemon/dlt-daemon.c

dlt-daemon: fix compile error with DLT_IPC="UNIX_SOCKET"

---

src/lib/dlt_user.c
tests/gtest_dlt_user.cpp

Change the behavior of dlt_user_log_write_string,
dlt_user_log_write_constant_string and dlt_user_log_write_utf8_string
so that they truncate the incoming message if it is too big
and add "Message truncated, too long" at the end of it.
These function should anyway still return an DLT_RETURN_USER_BUFFER_FULL
error in this case.
Signed-off-by: Nguyen Dinh Thi (RBVH/ENG2) <Thi.NguyenDinh@vn.bosch.com>

libdlt: truncate the log message if it is too long (#156)

---

src/daemon/dlt_daemon_socket.c

The default INADDR_ANY is used ("0.0.0.0") as before.
But it's invalid when DLT_USE_IPv6 flag ON.

dlt-daemon: fix bug binding invalid ipv6 address as default

---

doc/CMakeLists.txt

dlt-control should generate a dlt-control manpage, not a dlt-system one

Update cmakelist, fix build due to copy-paste error

---

src/daemon/dlt_daemon_client.c
src/lib/dlt_filetransfer.c
src/offlinelogstorage/dlt_offline_logstorage_behavior.c
src/shared/dlt_common.c
src/shared/dlt_offline_trace.c
src/system/dlt-system-journal.c

Since localtime() was calling tzset() internally, it should be used
before localtime_r(). Refer to man page of localtime_r() for detail.

dlt-system: Call tzset before localtime_r

---

doc/dlt_design_specification.txt
src/lib/dlt_user.c
src/lib/dlt_user_cfg.h

Improvement: housekeeper thread with poll
- Change name receiver thread to housekeeper thread
- Use poll() in housekeeper thread to get new received message
from DLT Daemon.
- Remove resend buffer inside of dlt_user_log_reattach_to_daemon()
- Only try to resend buffer if fd is valid.
This commit removes the event driven dlt_user_log_reattach_to_daemon()
that is called e.g. by DLT_LOG. Now, only the DLT housekeeper thread
handles the retrial to attach to daemon.
Signed-off-by: Simon Herkenhoff <sherkenhoff@jp.adit-jv.com>
Signed-off-by: Bui Nguyen Quoc Thanh <Thanh.BuiNguyenQuoc@vn.bosch.com>

libdlt: reattachment and improvement in dlt thread (#114)

---

src/daemon/dlt-daemon.c
src/daemon/dlt_daemon_common.c

* Symptom: no offline trace file gets created
even if runtime config LoggingMode==(2|3).
* Reason: runtime config gets read *after*
offline logging setup.
* Solution: Read runtime config *before*
offline logging setup.
* Make the "read runtime config" function
set a proper default value for logging mode
instead if the *_init_* function setting up
the logging.
Signed-off-by: Sebastian Kloska <sebastian.kloska@snafu.de>

Fix: Propper usage of LoggingMode in ".../dlt-runtime.cfg"

---

include/dlt/dlt_offline_trace.h
src/shared/dlt_offline_trace.c

The function dlt_offline_trace_file_name() use sizeof the
pointer as the maximum file name size, so it cannot create
the file name as expected.

fix the dlt offline trace file name creation

---

include/dlt/dlt_common.h
src/shared/dlt_common.c
src/tests/dlt-test-client.c
tests/gtest_dlt_common.cpp

Description:
Avoided Seg fault by adding boundary check before buffer access.
Signed-off-by: Ravi Sankar P <ponnurangamravi.sankar@in.bosch.com>

Avoided Seg fault in dlt_message_payload (#179)

---

include/dlt/dlt_offline_trace.h
src/daemon/dlt-daemon.c
src/shared/dlt_offline_trace.c

Fix the issue that DLT offline trace creating mutiple files
even after reaching MaxTrace size when filename is index based.
Related to: https://github.com/GENIVI/dlt-daemon/pull/174

dlt-offline-trace: fix bug and hardcode (#174)

---

AUTHORS
src/system/dlt-system-filetransfer.c

This potential memory leak in dlt-system-filetransfer.c can happen if only a filename
is passed to dirname(). In the current implementation of dlt-daemon, this issue cannot happen.
But in case of refactoring or different usage there is a chance that it can be triggered.
See: https://linux.die.net/man/3/dirname
Andreas Seidl <andreas.seidl@daimler.com>, Mercedes-Benz AG on behalf of MBition GmbH
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md
Licensed under MPL-2.0

Fix a potential memory leak in file transfer

---

include/dlt/dlt_common.h
src/daemon/dlt_daemon_client.c
src/gateway/dlt_gateway.c
src/shared/dlt_common.c

fixes #190
Changing the `DLT_CHECK_RCV_DATA_SIZE` macro into a static inline function requires to include `syslog.h` (due to the use of `LOG_WARNING`) and to declare `dlt_vlog()` earlier. Therefore, I think it's acutally best to just change this macro into an internal function.

Change DLT_CHECK_RCV_DATA_SIZE macro to an internal function

---

include/dlt/dlt_offline_trace.h
src/shared/dlt_offline_trace.c

* Symptome: If access to the trace directory is not
granted by AppArmor access(...) still reports otherwise.
dlt_offline_trace_get_total_size(...)
tries to open the dir via opendir(...) and tries a
readdir without any further check, which results in an
SEGFAULT
* Solution: (1) Make dlt_offline_trace_get_total_size return
ssize_t instead of unsigned long, which gives us a
chance to return an error state (2) Check the return value
from opendir(...) and bail out on error. Use this to return
DLT_RETURN_ERROR in dlt_offline_trace_check_size.
* ToDo: (1) Error state is not yet checked and reported
back. On Error we just don't generate any offline
log files without any further complain. (2) Find a replacement
for access(...) which reports properly under AppArmor.
(3) Reoprt the confusing …

BugFix: SEGFAULT when using AppArmor

---

src/daemon/dlt.conf

There are some warnings while running dlt-daemon:
$dlt-daemon
Unknown option: UDPConnectionSetup=1
Unknown option: UDPMulticastIPAddress=225.0.0.37
Unknown option: UDPMulticastIPPort=3491
cause the WITH_UDP_CONNECTION is not enabled by default (c9d1ba4b).
The configuration for this feature should be sync.
Signed-off-by: Phong Tran <tranmanphong@gmail.com>

dlt.conf: suppress the warnings udp multicast

---

include/dlt/dlt_user_macros.h

The GNU preprocessor supports naming of the variadic macro parameter,
but not all preprocessors do.
Signed-off-by: Ted Lyngmo <ted@lyncon.se>

Remove naming of variadic macro parameters

---

doc/dlt_for_developers.md

Fixes the problem that users are not able to use DLT with the include directive `#include <dlt/dlt.h>` that is stated in the developer guide (see `doc/dlt_for_developers.md`).
This is required in order to build other GENIVI projects like (vsomeip, capicxx-core-runtime, ...) without any problems since they all seem to use the include directive mentioned above.

doc/dlt_for_developers.md: Fix wrong include directive

---

src/shared/dlt_common.c

Check for file == null before accessing the pointer
for a debug message
Signed-off-by: Sebastian Kloska <sebastian.kloska@snafu.de>

FIX: Check validity of `file` pointer before usage.

---

src/shared/dlt_common.c

A DLT lib user can create a message large enough that `dlt_user.resend_buffer` is not large enough, and thus it will overflow.
Signed-off-by: Ricardo Leite <rleite@dcc.fc.up.pt>
Seen some crashes where this turned out to be the root cause.

dlt_common: Fix buffer overflow in dlt_buffer_get

---

src/shared/dlt_common.c

The log message was printed as a signed value for uint64 type. This
commit fixes to print as an unsigned value.

common: Fix uint64 type

---

src/daemon/dlt-daemon.c

On a new client connection, `dlt_daemon_log_internal` is called with with a null `local_str`.
There are no side effects, apart empty lines in DLT viewer.
The mistake was introduced in a refactoring. I have reverted those lines to the [previous version](https://github.com/GENIVI/dlt-daemon/commit/bfa7026b355db32d91374997cc86b56fedc3e861#diff-11985d537fb773028c45cf71c649f660L1662).

Fixed internal empty message

---

doc/dlt_for_developers.md
include/dlt/dlt_user.h
include/dlt/dlt_user_macros.h
src/lib/dlt_user.c
tests/gtest_dlt_user.cpp

This use case is common in C++ code nowadays, due to the usage of e.g.
std::string_view, which does not provide a function for retrieving a
null-terminated C-string, but which provides quick access to the string
length via std::string_view::size().
Such use cases can now avoid an entirely unnecessary strlen() call.

Add sized string functions

---

src/lib/dlt_user.c

Signed-off-by: Rudolf Svanda <rudolf.svanda@globallogic.com>

FIX: prevent usage of uninitialized message queue handle

---

.travis/gtest_dlt_all.sh

Currently the gtest_dlt_all.sh script bypass any core dumped errors if it exists. This change helps TravisCI to detect that error.

Update gtest_dlt_all.sh to detect core dump

---

src/lib/dlt_user.c

To totally solve the issue [237](https://github.com/GENIVI/dlt-daemon/issues/237), the DLT_NETWORK_TRACE_ENABLE should be added before starting the segmented thread.
The cause of lacking this definition could be due to my mistake when updating minor version 2.18.4 to 2.18.5
Signed-off-by: KHANH LUONG HONG DUY <khanh.luonghongduy@vn.bosch.com>

dlt_user.c: fix the lack of DLT_NETWORK_TRACE_ENABLE definition

---

systemd/3rdparty/sd-daemon.c

Reported by Khem Raj on meta-oe list
TOPDIR/build/tmp/work/armv7vet2hf-neon-yoe-linux-musleabi/dlt-daemon/2.18.5-r0/recipe-sysroot/usr/include/sys/fcntl.h:1:2: error: redirecting incorrect #include <sys/fcntl.h> to <fcntl.h> [-Werror,-W#warnings]
^
1 error generated.
Signed-off-by: Gianfranco Costamagna <costamagnagianfranco@yahoo.it>
Signed-off-by: Gianfranco Costamagna <locutusofborg@debian.org>

sd-daemon.c: Fix build with newer glibc and musl libc

---

src/offlinelogstorage/dlt_offline_logstorage.h

see bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=957140
/usr/bin/ld: CMakeFiles/dlt-daemon.dir/dlt_daemon_client.c.o:./obj-x86_64-linux-gnu/src/daemon/./src/offlinelogstorage/dlt_offline_logstorage.h:116: multiple definition of `g_logstorage_cache_max'; CMakeFiles/dlt-daemon.dir/dlt-daemon.c.o:./obj-x86_64-linux-gnu/src/daemon/./src/offlinelogstorage/dlt_offline_logstorage.h:116: first defined here
/usr/bin/ld: CMakeFiles/dlt-daemon.dir/dlt_daemon_common.c.o:./obj-x86_64-linux-gnu/src/daemon/./src/offlinelogstorage/dlt_offline_logstorage.h:118: multiple definition of `g_logstorage_cache_size'; CMakeFiles/dlt-daemon.dir/dlt-daemon.c.o:./obj-x86_64-linux-gnu/src/daemon/./src/offlinelogstorage/dlt_offline_logstorage.h:118: first defined here
/usr/bin/ld: …

dlt_offline: fix build failures with gcc-10

---

CMakeLists.txt

nto-qnx matches architecture "sub-binaries" for qcc, but can also invoke with qcc binary and specify architecture. The CMake documentation has an example for a QNX toolchain file that sets CMAKE_C_COMPILER to qcc, so it is probably very common. See:
https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-qnx
Not sure why this check is needed. (Is qcc really the only compiler that can be used to build for QNX?) An alternative could be to remove it completely.

Modify CMAKE_C_COMPILER check for QNX to accept "qcc"

---

src/lib/CMakeLists.txt

By calling `target_include_directories()` for the `dlt` target in `src/lib/`. CMake filters out duplicate include paths. So even if the include directories are already added with `include_directories()` in the top-level `CMakeLists.txt`, they are not duplicated when the compiler is invoked.
For example, with this patch, the following works:
```bash
[~/Source/foo]$ ls
bar  CMakeLists.txt  dlt-daemon
[~/Source/foo]$ cat CMakeLists.txt
cmake_minimum_required(VERSION 3.3 FATAL_ERROR)
project(foo)
add_subdirectory(dlt-daemon)
add_subdirectory(bar)
[~/Source/foo]$ cat bar/CMakeLists.txt
cmake_minimum_required(VERSION 3.3 FATAL_ERROR)
project(bar)
add_executable(bar main.cpp)
target_link_libraries(bar dlt)
install(TARGETS bar RUNTIME DESTINATION bin)
```
`bar/main.cpp` contains the example from …

Make it easier to use libdlt when building DLT as a CMake subproject

---

src/shared/dlt_common.c

make sure strncpy writes a null terminated string

dlt-common.c: ensure null terminated string

---

src/console/dlt-control.c

this make the code easier to read and
initializes all other variables with 0

dlt-control.c: initialize dltdata via struct literal

---

Android.bp

Can not see `src/daemon/dlt_daemon_filter.c` in history. Not sure where it comes from. Internal branch used by submitter of initial Android.bp?

Remove nonexistent file from Android.bp

---

src/daemon/dlt_daemon_socket.c

Change warning to error, as it will abort the daemon startup.
Also reduce the amount of follow up error messages. 

dlt-daemon.c: exit early on error

---

src/examples/dlt-example-user.c

atoi(dvalue) * 1000000 overflows if given a value >= 2147 when sizeof(int) is 4. (2^31 / 10000000 ~= 2147.48)

Fix overflow for -d argument in dlt-example-user

---

src/lib/dlt_client.c

Several IP address might be tested for connect.
Only output an error if no address succeeds at all.

dlt_client.c: remove misleading error message

---

include/dlt/dlt_common.h
src/shared/dlt_common.c
tests/gtest_dlt_common.cpp

This changeset fixes a memory access error reported by valgrind:
==21924== Conditional jump or move depends on uninitialised value(s)
==21924==    at 0x4C30F78: strlen (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==21924==    by 0x4E4B5A0: dlt_print_id (dlt_common.c:303)
==21924==    by 0x4E4CF47: dlt_message_header_flags (dlt_common.c:687)
==21924==    by 0x4E51434: dlt_message_print_ascii (dlt_common.c:3169)
==21924==    by 0x4E4247A: dlt_user_print_msg (dlt_user.c:4108)
==21924==    by 0x4E46D92: dlt_user_log_send_log (dlt_user.c:3670)
==21924==    by 0x4E46F14: dlt_user_log_write_finish (dlt_user.c:1611)

Fix valgrind memory issue

---

src/android/dlt-logd-converter.cpp

Some improvements for android adapter
- Earlier the crash buffer wasn't initalized,
claimed to be binary which isn't true.
https://cs.android.com/android/platform/superproject/+/master:system/logging/logcat/logcat.cpp;drc=5837d33d1cfecce0632e385c8ede89c02685238f;l=194
- Also no need register buffers which isnt used.
- Adds message length check to handle malformed message.

Android adapter: Init missing buffer + message length check

---

doc/dlt.conf.5.md
src/daemon/dlt-daemon.c
src/daemon/dlt-daemon.h
src/daemon/dlt.conf
src/daemon/dlt_daemon_client.c

A new option named "InjectionMode" allows to select if we want to enable / disable the feature.

dlt-daemon: Adds an option to disable injection mode

---

src/shared/dlt_common.c

A buffer overflow in the dlt_filter_load function in dlt_common.c in dlt-daemon allows arbitrary code execution via an unsafe usage of fscanf, because it does not limit the number of characters to be read in a format argument.
Fixed: #274
Signed-off-by: GwanYeong Kim <gy741.kim@gmail.com>

dlt_common: Fix buffer overflow in dlt_filter_load

---

src/console/dlt-control.c

Not sure if this is a desired behavior, but it seems logical to return an error exit code if an error occurs. 

dlt-control.c: return -1 on error

---

README.md

travis-ci.org will be shutting down within few weeks. Migrating to travis-ci.com.

README: Switch from travis-ci.org to travis-ci.com

---

src/daemon/dlt-daemon.c

Security-wise the dlt pip(FIFO) should be exclusively only readable by user owner not the whole group,
in order to prevent eavesdropping by clients

Make dlt pipe readable only by owner

---

src/shared/dlt_common.c

fscanf() uses dynamic formatting to prevent buffer overflow which is mentioned in CVE-2020-29394

fscanf() uses dynamic formatting to prevent buffer overflow

---

doc/dlt-receive.1.md
src/console/dlt-receive.c

This allows the dlt-receive command line tool to be used if the dlt-daemon is not listening on the default port.

dlt-receive: Add option to configure port of dlt receive

---

src/shared/dlt_common.c

Previously, the bytes of a RAWD argument were be printed onto the console
as space-separated hex values, making it difficult or impossible to see
where the RAWD argument ends and the next argument starts. For instance,
with code like this:
dlt_user_log_write_raw(&ctxData, "data", 4);
dlt_user_log_write_uint8(&ctxData, 53);
the console output is shown as:
[64 61 54 61 53]
and there is no indication that there are two arguments, one RAWD and
one UINT8.
This patch changes for console formatting of RAW data to separate by
apostrophs, making the above message appear as:
[64'61'54'61 53]
This makes it immediately obvious that there is a RAWD argument, and
still keeps the separators quite unobtrusive.
Signed-off-by: Martin Willers <M.Willers@gmx.net>

Better formatting of RAWD

---

automotive-dlt-config.cmake.in
doc/dlt_for_developers.md
src/lib/CMakeLists.txt

Create and install proper CMake *-target.cmake and *-config.cmake files,
for use by other CMake-using projects.

Export cmake config file

---

automotive-dlt.pc.in
doc/dlt_for_developers.md

Previously, an application using this library's pkg-config setting for
include directory would only get e.g. -I/usr/local/dlt/include/dlt
With that include dir, the application needs to write its #include
statements without any prefix, i.e. "#include "dlt_user.h"
This is considered bad practice for header files of an elaborate
library consisting of multiple header files.
For such libraries, one should write #include statements like
this: #include "dlt/dlt_user.h", i.e. prefix it with a directory.
This commit achieves that by letting the pkg-config module also return
the upper-level directory in addition to the previous one.
For instance, the include directive returned by the above example
would now be "-I/usr/local/dlt/include -I/usr/local/dlt".
Closes #318
Signed-off-by: Martin Willers …

Extend include path in *.pc file

---

src/lib/dlt_user.c

Fixing casting incorrect type
Signed-off-by: Dinh Cong Toan <toan.dinhcong@vn.bosch.com>

dlt_user.c: fixing casting wrong type

---

include/dlt/dlt_filetransfer.h
src/lib/dlt_filetransfer.c

If a file is deleted while a file transfer is ongoing,
the file transfer tries to seek through the whole file.
This is due to the fact the the file handle is held open.
getFileSerialNumber is already validating the file
by using stat.
If this call returns a negative value, we know
that a stat to the file is not possible anymore,
therefore further reading can be aborted.
Alexander Mohr, [alexander.m.mohr@daimler.com](mailto:alexander.m.mohr@daimler.com), Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)

file-transfer: Abort file transfer if get serial number failed

---

doc/dlt_for_developers.md
src/lib/CMakeLists.txt

Previously the generated .pc file was changed to export an additional include path such that '#include <dlt.h>' and '#include <dlt/dlt.h>' can be used. However the exported CMake config file only supports the latter include statement. Consequently code that uses the other legacy include statement does not compile with the exported CMake config file.
This change fixes this inconsistency. It lets users compile existing code with either the pkg-config .pc file or the CMake config file and avoids code clutter that is currently necessary to make this work.
See also #318, #319.

libdlt: Add legacy include path in exported CMake config file

---

CMakeLists.txt
doc/dlt_for_developers.md
src/lib/CMakeLists.txt

Keep the generated CMake config file "clean" in that only `<prefix>/include/` is being added to the compiler's header search path by default. If the legacy include path, i.e. `<prefix>/include/dlt/`, is also to be added, then use the CMake option `-DWITH_LEGACY_INCLUDE_PATH=On`.
See also #327, #319, #318
Signed-off-by: Martin Willers <M.Willers@gmx.net>

Make the legacy include path a CMake option

---

src/daemon/dlt-daemon.c

The problem is described at https://github.com/GENIVI/dlt-daemon/issues/341. Scan of port 3490 from a Linux machine by
'nmap -v -p 3490 -Pn IP_address_of_QNX_board' leads to dlt-daemon crash.
The solution:
It is necessary to parse the code of the returned error in errno. If errno = ECONNABORTED it means there was an attempt to scan port 3490 and on this error there is no need to exit the application by error.

fix for the issue #341

---

src/dlt-qnx-system/dlt-qnx-slogger2-adapter.cpp

Problem:
Some QNX components when bringing up send messages of severity type "FATAL" instead of "INFO" via slogger2 . 
Root Cause:
QNX component send messages of payload data_type = SLOG2_TYPE_ONLINE. The buffer is new and just came online.
dlt-qnx-slogger2 does not support info->data_type = SLOG2_TYPE_ONLINE and therefore sets the wrong log level.
Solution:
Forcibly change the severity level for all info->data_type = SLOG2_TYPE_ONLINE to SLOG2_INFO.

Forcibly the severity level set

---

src/lib/dlt_user.c
src/shared/dlt_common.c

This PR is about fixing compilation issues detected with clang on android 10 toolchain where -Werror and -Wformat are activated
* some previous dlt_vlog was using %lu specifier to display an uint64_t variable. However, this isn't portable as depending on the system you're targeting (32bits, 64bits, Linux, android, etc.), the uint64_t can be an unsigned long long. This prevents compilation on system where -Werror and -Wformat is activated coupled with a less tolerant compiler (e.g clang). Instead, PRIxN macros (e.g PRIu64 for uint64_t) are now used as specifier to ensure compatibility for each platforms
* for bytes_read which is of type ssize_t, zd specifier is used as indicated in C99 standard
* for st_size (from struct stat) which is of type off_t, POSIX says that it should be a signed …

fix -Wformat issues reported by clang

---

src/system/dlt-system-options.c
src/system/dlt-system.h

The unused variable caused a segmentation fault at program exit when the default value was being used, since it was not initialized to NULL and the structure containing it was being used from a local context.

dlt-system: fix invalid free by removing unused TempDir

---

src/daemon/CMakeLists.txt
src/daemon/dlt-daemon.c
src/daemon/dlt_daemon_common.c
src/lib/CMakeLists.txt
src/shared/dlt_common.c
src/tests/dlt-test-client.c
src/tests/dlt-test-multi-process-client.c
src/tests/dlt-test-multi-process.c
src/tests/dlt-test-stress-client.c
tests/CMakeLists.txt

Also tested with the latest version running on Windows XP (gcc-5.4.0)
(http://www.crouchingtigerhiddenfruitbat.org/cygwin/timemachine.html).

Support for Cygwin toolchain.

---

src/tests/dlt-test-client.c
src/tests/dlt-test-user.c

- Fix DLT Test Client expected string in Test 5 (for #291)
- Fix DLT Test User Disable Macro usage: `#cmakedefine01 DLT_DISABLE_MACRO` (from `dlt_user.h.in`) still defines the macro even though DLT_DISABLE_MACRO is not set inside CMake.

Fix DLT User/Client tests

---

CMakeLists.txt
src/console/CMakeLists.txt

This commits adds several cmake options to enable or disable
each console tool separately.
<sup>Alexander Mohr, <alexander.m.mohr@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

cmake: Add options to enable/disable each dlt console tool

---

src/lib/dlt_filetransfer.c

Setting `date = 0;` and continuing the function execution will cause a segmentation fault when calling `asctime_r(&ts, date)`.

filetransfer: Fix getFileCreationDate2 stat check

---

src/shared/dlt_config_file_parser.c

In the dlt_config_file_set_section  function of  dlt_config_file_parser.c,  the following code exists:
s-name is not set to null after free.
It will be freed again in the dlt_config_file_release function.

dlt_config_file_parser.c：Fix a pointer release bug in the file。

---

src/console/dlt-convert.c
src/console/dlt-sortbytimestamp.c
src/shared/dlt_common.c

In some cases, if the returned value is not handled, it could cause the unexpected read and write operation to memory.

Fix handle returned value

---

automotive-dlt.pc.in

Make the user find the static library by pkg-config, when BUILD_SHARED_LIBS=OFF.

automotive-dlt.pc: add the path to find the static library

---

src/daemon/dlt-daemon.c
src/daemon/dlt-daemon.h

if an application sends a message with a level below context level
and the level enforcement is on, the message will be dropped

enforce-trace-limit: ContextLogLevel is now enforced in the daemon

---

src/daemon/dlt-daemon.c

dlt-daemon allows configuration of multiple addresses.
Before this commit the daemon exits when the first binding fails.
This commit changes the behavior so that the daemon only exits
if none of the configured addresses can be opened.

dlt-daemon-connection: Start up even if not all bindings are valid

---

src/shared/dlt_common.c

Up to now the default for logging is stdout (DLT_LOG_TO_CONSOLE).
Scenario:
program_a arg1 | dd of=/my-beauty-case
If program_a wants to log to dlt, but it fails to connect to the socket: socket /run/dlt-files/dlt cannot be opened, error:Resource temporarily unavailable. Retrying later...
The error will be logged by default to stdout leading in the best case to an error and in the worst to damaged partitions.
To solve this log to STDERR (DLT_LOG_TO_STDERR) by default.

dlt_common.c: Change default logging_mode

---

src/offlinelogstorage/dlt_offline_logstorage.c

This commit prevents a buffer overflow in case the supplied ECUID inside a Logstorage filter .conf file is larger than 4 bytes because it is currently not truncated anywhere else.

logstorage: Truncate ECUid in Logstorage filter to prevent crash

---

src/daemon/dlt-daemon.c
src/gateway/dlt_gateway.c

* dlt-gateway crashed when an invalid
ip address was configured as a null pointer
was used for strdup
* Add timeout for dlt-client-connect.
Timeout is hard coded to 1 seconds to prevent blocking
the dlt-daemon overly long if a timeout is happening
while creating a gateway connection.

dlt-gateway: Fix crash on invalid ip

---

src/daemon/dlt_daemon_client.c

- Type of return value of strncmp() is int
- Should replace int8_t by int to avoid error when casting
Signed-off-by: Le Tin <tin.le@vn.bosch.com>

dlt_daemon_client: Fix change loglevel of application

---

CMakeLists.txt
src/daemon/CMakeLists.txt
src/daemon/dlt_daemon_unix_socket.c
systemd/CMakeLists.txt
systemd/dlt.socket.cmake

dlt-daemon now support activation via systemd socket.
This allows dlt-daemon to be started as soon as an application
is requesting access to the dlt socket.
This commits implements opening the socket only when
UNIX_SOCKET is used for IPC

systemd: add support for socket activation via systemd

---

CMakeLists.txt
include/dlt/dlt_common.h
src/daemon/dlt-daemon.c
src/daemon/dlt.conf
src/shared/dlt_common.c

This commit fixes the following issues if access
to the internal log file is not possible (logging_mode = DLT_LOG_TO_FILE)
* dlt_log_free tried to call fclose on a nullptr
Added a nullcheck for this
* Access to log file might be denied but access to logs is still wanted
Add a new CMake option WITH_DLT_FILE_LOGGING_SYSLOG_FALLBACK
If this is set to ON and the logging moe is set to file,
the dlt-daemon will fall back to syslog if opening the internal log
file failed

internal-logging: Fix issues with file logging

---

src/shared/dlt_common.c

Switch dlt_vlog() to dlt_user_printf(), the message could be observed in case the log can not be written in file
Signed-off-by: Le Tin <tin.le@vn.bosch.com>

dlt_common: change output of message for log initialization

---

include/dlt/dlt_common.h
src/console/dlt-control.c
src/lib/dlt_client.c
src/shared/dlt_common.c
tests/gtest_dlt_common.cpp

- Introduced new function dlt_getloginfo_conv_ascii_to_string for '\0' terminated strings
- Avoid printing garbage characters in dlt-control after APID and CTID (which are not null terminated anymore)
- Added unit test for dlt_client_parse_get_log_info_resp_text and dlt_getloginfo_conv_ascii_to_string

Avoid memory corruption behind buffer wp in function dlt_getloginfo_conv_ascii_to_id

---

src/daemon/dlt_daemon_client.c

Fixes wrong `strcmp()` usage with non-NULL terminated `extra.ecu`.

dlt_daemon_client: Fix Control Msg ECUId comparison with active Gateway

---

src/daemon/dlt-daemon.c
src/daemon/dlt_daemon_client.c
src/daemon/dlt_daemon_offline_logstorage.c
src/lib/dlt_user.c
src/shared/dlt_config_file_parser.c
src/shared/dlt_offline_trace.c

dlt_daemon_client.c Adding NULL check for tok
dlt_daemon_offline_logstorage.c : Adding NULL check for application 
dlt_user.c : Fix for Memory Leak
dlt-daemon.c : Fix for Resource Leak
dlt_config_file_parser.c : Add termination character at the end of string 
dlt_offline_trace.c : Fix for Resource Leak
Signed-off-by: Mvaradaraj2 manoj.varadaraj2@harman.com

Fix for Resource and Memory Leak

---

src/system/dlt-system-watchdog.c

On 32bit target, dlt-system will termiated with error:
dlt-system: *** buffer overflow detected ***: terminated
Signed-off-by: Changqing Li <changqing.li@windriver.com>

dlt-system: Fix buffer overflow detection on 32bit targets

---

CMakeLists.txt

Add cmake toggle to disable network trace.
So you can disable the dlt_segmented-thread and improve the performance of system.
<sup>Daniel Weber, [daniel.w.weber@mercedes-benz.com](mailto:daniel.w.weber@mercedes-benz.com), Mercedes-Benz Technology Innovation GmbH, [imprint](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)</sup>

cmake: network trace enable toggle

---

src/lib/dlt_client.c
src/shared/dlt_common.c

Fix wrong cast in `dlt_getloginfo_conv_ascii_to_uint16_t` which would lead to a crash if the read value would be more than 255.
Fix missing `count_app_ids = 0` in` dlt_client_free_calloc_failed_get_log_info` which causes a crash if this method would be called, as the final de-init method will iterate again and access free'd memory.

client: Fix Get Log Info response conversion method

---

src/lib/dlt_filetransfer.c

If the file size is divisible by the package size don't send one empty FLDA.
Also we send the correct number of FLDAs too.
<sup>Daniel Weber, [daniel.w.weber@mercedes-benz.com](mailto:daniel.w.weber@mercedes-benz.com), Mercedes-Benz Technology Innovation GmbH, [imprint](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)</sup>

filetransfer: fix filesize divisible by blocksize case

---

src/gateway/dlt_gateway.c

Reset Receiver at connection close to prevent corruption: a partial log may be received from a Node, but in case there is an ECUid mismatch, the socket will be closed and that log will never be completed corrupting the receiver.
Prevent out of bounds reads
Fix connection select when processing passive node messages: fd's can use the same value for a new connection if a previous connection is closed so we need to also select based on connection status

gateway: Fix Node handling and ECUid checks

---

src/lib/dlt_user.c
tests/gtest_dlt_user.cpp

If dlt_free is called while dlt_init is running, the dlt-user library
crashes because the init and free where not thread safe.
This commit introduces a new field dlt_user_initialising
which will prevent entering dlt_free while dlt_init is running.
Correctness is ensured by a unit test

dlt-user: Fix crashes in dlt_free during dlt_init

---

src/console/dlt-convert.c

Free the index which already allocated memory in dlt_file_read phase
Signed-off-by: Le Van Khanh <Khanh.LeVan@vn.bosch.com>

dlt-convert: Fix memory leak by calling dlt_file_free

---

src/lib/dlt_user.c

wait until the house keeper is up and running
this makes sure dlt_init / dlt_free in close succession closes this thread properly.
Otherwise we might keep the dlt socket open
Check if the thread is running every 10ms

dlt-user: fix potential non closed socket in init/free

---

src/console/dlt-control-common.c

Free the ecuid_conf in case of memory alllocated
Signed-off-by: Le Van Khanh <Khanh.LeVan@vn.bosch.com>

Fix memory leak

---

src/daemon/dlt_daemon_connection.c

in some scenarios a socket might block forever.
This means dlt-daemon won't respond properly anymore. To fix this a timeout is added to the dlt-daemon socket connection.

dlt-connection: add socket timeout

---

Android.bp
src/android/dlt-logd-converter.cpp

This PR is about fixing a compilation issue which appear starting on android 12 for android-logd-converter
* Since android 12 release (and the introduction of this [commit](https://chromium.googlesource.com/aosp/platform/system/logging/+/b674866203f05957b2ac5db94c3c0fe3d1d36793)), the macro ANDROID_LOG_RDONLY and friends have been removed (see the commit for the explanation). Therefore, dlt-logd-converter can't compile anymore since this version.
* The modification have been made in such way to allow dlt-logd-converter to compile also on version prior to android 12

dlt-logd-converter: fixes android 12 compilation

---

src/lib/dlt_user.c

make sure that a string with exactly UINT16_MAX bytes does not overflow the dlt buffer
Given the example below there is a crash is libdlt 
```c++
#include <dlt/dlt.h>
#include <cstring>
#include <string>
DLT_DECLARE_CONTEXT(mycontext)
int main()
{
DLT_REGISTER_APP("FOOB", "TEST DEMO");
DLT_REGISTER_CONTEXT(mycontext, "CTX1", "Test Context for Logging");
size_t len = 65535;
char* txt = (char*)malloc(len);
memset(txt, 'c', len);
// will crash
DLT_LOG(mycontext, DLT_LOG_INFO, DLT_STRING(txt));
}
```
The expansion of the macro looks like this
```c
do {
DltContextData log_local;
int dlt_local;
dlt_local = dlt_user_log_write_start(&mycontext, &log_local, DLT_LOG_INFO);
if (dlt_local == DLT_RETURN_TRUE) {
(void)dlt_user_log_write_string(&log_local, txt); …
```

dlt-user: fix crash with certain strings

---

src/daemon/dlt-daemon.c

Re-Initialize internal logging is triggered twice during startup. This fixed might be a simplified initailization code for DLT.

Re-Initialize internal logging in daemon mode only

---

src/system/dlt-system-process-handling.c

DLT_LOG is using internally function which are not async-signal safe (like calloc, vsnprintf). Therefore, it needs to be removed from the signal handler

Remove use of DLT_LOG in signal handler

---

README.md

The current link might be dead (error 503): https://www.autosar.org/fileadmin/user_upload/standards/classic/4-0/AUTOSAR_SWS_DiagnosticLogAndTrace.pdf
Replacing with working link of an updated version 4 of the standard: https://www.autosar.org/fileadmin/standards/R22-11/CP/AUTOSAR_SWS_DiagnosticLogAndTrace.pdf

Update AUTOSAR standard link

---

CMakeLists.txt

this version will be used to create filenames etc
and should reflect the current version

cmake: set version to 2.18.9

---

include/dlt/dlt_common.h
include/dlt/dlt_cpp_extension.hpp
include/dlt/dlt_user.h.in
include/dlt/dlt_user_macros.h
src/daemon/dlt_daemon_common.h
src/lib/dlt_user.c

Fix macro code  to use boolean value in while instruction (false)
Fixes #308 

Fix macro code  to use boolean value in while instruction (false)

---

CMakeLists.txt
src/daemon/dlt_daemon_client.c
src/daemon/dlt_daemon_common.c
src/shared/dlt_user_shared.c
src/shared/dlt_user_shared.h

This timeout is necessary to prevent
blocking writev indefinitely.
Without the timeout dlt-daemon, may block
indefinitely when an app id is re-used
very frequently.
In that case dlt-daemon won't accept anymore
new connections and further communication
in any way is not possible anymore.

dlt_user_shared: Add timeout to writev

---

CMakeLists.txt
automotive-dlt.pc.in

adding static library should only be enabled
if the dlt library is build static.
Adding this to the automotive-dlt.pc.in
when static libraries are disabled
yocto build will break

build: add static lib only if necessary

---

CMakeLists.txt
doc/dlt_build_options.md
src/daemon/dlt-daemon.c
src/daemon/dlt_daemon_client.c
src/daemon/dlt_daemon_common.c
src/daemon/dlt_daemon_common.h
src/system/dlt-system-journal.c
src/system/dlt-system-process-handling.c
src/system/dlt-system-watchdog.c
src/system/dlt-system.h

* watchdog can be configured to notify systemd only if messages are received
* activate this via:
* -DWITH_SYSTEMD_WATCHDOG_ENFORCE_MSG_RX=ON
* -DWITH_SYSTEMD_WATCHDOG_ENFORCE_MSG_RX_DLT_SYSTEM=ON

watchdog: improve dlt watchdog

---

tests/gtest_dlt_daemon_gateway.sh

- dlt-daemon cannot open dlt_passive.conf file because there is no this file in gtest_dlt_daemon_gateway.sh
- Should run dlt-daemon under darmonize mode

gtest_dlt_daemon_gateway: dlt-daemon run without dlt_passive.conf file

---

tests/CMakeLists.txt
tests/gtest_dlt_daemon_gateway.cpp
tests/gtest_dlt_daemon_offline_log.cpp
tests/gtest_dlt_user.cpp
util/gcov/gcov.sh

+ Fix issues offline log unit test fail when not trigger gzip feature
+ Add timeout to prevent timeout silently ignored
+ Limit dlt_user final test suite to 5 seconds
+ Fix wrongly triggered gtests with environment (gateway+offline)

dlt_unit_test: Fix and improve quality of unit tests

---

doc/dlt-qnx-system.md
src/dlt-qnx-system/dlt-qnx-slogger2-adapter.cpp
src/dlt-qnx-system/dlt-qnx-system.c

- QNX:Injection for dlt-qnx-system
Introduce injection messages for dlt-qnx-system
It helps to completely disable parsing slog2 entries in some unnecessary cases.
- dlt-qnx-system:potential leaks
memory ctxt is allocated via new operator but
there is no place delete later
Use static variable instead of dynamic
- dlt-qnx-system:memory improvement
It seems that in a rare case the stack memory could face unexpected issue Try to use heap memory instead of stack
- dlt-qnx-system:release memory in teardown
The local stack variable to handle context map is handled incorrectly Solution is to apply an improvement with head memory and release memory properly
- qnxsystem: Correct arguments

dlt-qnx-system improvement

---

src/console/dlt-control-common.c

Fix compile error stringop-truncation with GCC 9.4

---

CMakeLists.txt

New googletest 1.13.0 defaults to gnu++14, so makes this package FTBFS when building testsuite with this error:
In file included from /usr/include/gtest/gtest-message.h:57,
from /usr/include/gtest/gtest-assertion-result.h:46,
from /usr/include/gtest/gtest.h:64,
from /build/1st/dlt-daemon-2.18.9/tests/gtest_dlt_user.cpp:27:
/usr/include/gtest/internal/gtest-port.h:270:2: error: #error C++ versions less than C++14 are not supported.
270 | #error C++ versions less than C++14 are not supported.
|  ^~~~~
Thanks Adrian Bunk <bunk@debian.org> for the report and the fix!

Update CMakeLists.txt: set required std version to gnu++14

---

CMakeLists.txt

Starting in CMake 3.20, CMake prefers all source files to have their extensions explicitly listed (.c,.cpp,etc). To keep dlt-daemon silently built, set this Policy to OLD.

cmake: Policy CMP0115 set to OLD behavior for dlt-daemon with cmake >= 3.20

---

src/console/dlt-control-common.c
src/lib/dlt_user.c

pthread_cond_timedwait has to be called with a locked mutex using an unlocked mutex is undefined behaviour
although it works on many platforms

fix usage of pthread_cond_timedwait

---

.github/workflows/codeql-analysis.yml

CodeQL Action v1 was deprecated on January 18th, 2023.
Hence update to v2, remove HEAD^2 due to update instructions.
Signed-off-by: LUU QUANG MINH <Minh.LuuQuang@vn.bosch.com>

codeql: Replace depricated Action v1 with v2

---

src/tests/CMakeLists.txt

Remove duplicated cpp extension setup.

cmake: Fix CMP0002 policy violation

---

src/daemon/dlt-daemon.c
src/daemon/dlt_daemon_connection.c

if a client disconnects at exactly the wrong time
we do not set a propper timeout for the socket
and do not disconnect the client either.
this commit removes the client connection
when setting the timeout failed.

connection: close connection when timeout cannot be set

---

tests/gtest_dlt_daemon_gateway.cpp

When converting ascii to unint16_t, the byte order needs to be kept for big-edian case
Reworked from: https://github.com/COVESA/dlt-daemon/pull/526

unittest: apply big-edian case for converting ascii to uint16_t 

---

src/daemon/dlt-daemon.c
src/daemon/dlt-daemon.h
src/daemon/dlt.conf

Add ECUSoftwareVersionFileField option to dlt.conf
Modify dlt_daemon_local_ecu_version_init() to read a single field from
KEY=VALUE (or quoted KEY="VALUE") style files, so that dlt-daemon can
report an OS version number parsed from /etc/os-release file.
For example, get_software_version would return "22.04.3 LTS" under the
following configuration:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION="22.04.3 LTS"
VERSION_CODENAME=jammy
$ cat /etc/dlt.conf
PathToECUSoftwareVersion = /etc/os-release
ECUSoftwareVersionFileField = VERSION

Add ECUSoftwareVersionFileField option to dlt.conf

---

doc/dlt_offline_logstorage.md
src/offlinelogstorage/dlt_offline_logstorage.c
src/offlinelogstorage/dlt_offline_logstorage.h
src/offlinelogstorage/dlt_offline_logstorage_behavior.c
src/offlinelogstorage/dlt_offline_logstorage_internal.h
tests/components/logstorage/logstorage_one_file/dlt.conf.in
tests/gtest_dlt_daemon_offline_log.cpp

Current implementation facing issue generating gzip dlt log, hence fix is applied:
+ Fsync for gzip
+ Adapt option parsing of gzip with others
+ Align gzip option status (on,off,default,unknown)
+ Make gzip a dlt proprietary

logstorage: Fix issue with gzip

---

util/create_dlt_version_h.py

Update git describe to always produce some output. This allows to ignore git warnings and errors.
Fix problem when git warning about tag get placed in C++ header and a syntax error breaks build.
Example git output that prodcues compilation errors:
> git describe --tags
warning: tag 'haleytek/v2.18.5' is externally known as 'v2.18.5' v2.18.5-19-g344c37b

Fix generating dlt version tag

---

include/dlt/dlt_user.h.in
src/lib/dlt_user.c

The current implementation of signaling mechanism
with binary semaphore is used to lock the libdlt ring buffer.
However, this cannot perform a correct locking.
While libdlt ring buffer is being freed by atexit_handler thread,
logging still happens in other threads dereferencing NULL pointers.
This fix replaces the current binary semaphore with a mutex lock,
folowing the locking mechanism.

dlt_user: race data happens between threads

---

include/dlt/dlt_filetransfer.h
src/examples/dlt-example-filetransfer.c
src/lib/dlt_filetransfer.c
tests/start_filetransfer_test.sh

dlt filetransfer cancelable with a bool flag added. added a new example application to test this function. modified shell script to run test easily.
This enables cancellation for example to shutdown faster.

filetransfer: function added for cancelable filetransfer

---

Android.bp

Binary "dlt-test-logstorage" doesn't have a source code and soong fails. This commit removes that binary.
Added two defines "DLT_WRITEV_TIMEOUT_SEC, DLT_WRITEV_TIMEOUT_USEC" that are used by dlt_user_shared.c"

Fix Android build issues

---

src/offlinelogstorage/dlt_offline_logstorage_behavior.c

Use strncat and strlen instead of strcat to avoid overflow of fixed size buffer.

Make sure copy into fixed size buffer does not overflow.

---

src/daemon/dlt-daemon.c

The return value of the function file_read_everything is char*.
In case of an error, NULL should be returned. If we return an integer we get an error:
`error: incompatible integer to pointer conversion returning 'int' from a function with result type 'char *' [-Wint-conversion]`
Also, returning -1 is not handled at the calling site and would result in the dlt_daemon_local_ecu_version_init function to return success where it should have returned a failure:
```
if (daemon_local->flags.ecuSoftwareVersionFileField[0] != '\0') {
daemon->ECUVersionString = file_read_field(f, daemon_local->flags.ecuSoftwareVersionFileField);
} else {
daemon->ECUVersionString = file_read_everything(f, DLT_DAEMON_TEXTBUFSIZE);
}
fclose(f);
return (daemon->ECUVersionString != NULL) ? 0 : -1;
```

Return error correctly when reading a file.

---

src/shared/dlt_multiple_files.c

The `newest` string may miss null-terminator, I assume it was supposed to be like this:
```
strncpy(newest, tmp_new, NAME_MAX);
newest[NAME_MAX] = '\0';
```
Note: the link in topic: `Please make sure to follow the [Rules for commit messages](https://at.projects.covesa.org/wiki/display/PROJ/Rules+for+Commit+Messages` does not work for me so commit message maybe incorrect. Error: `We can’t connect to the server at at.projects.covesa.org.`

dlt_multiple_files: Fix missing string null-terminator

---

src/daemon/dlt-daemon.c

dlt_daemon_process_user_message_log prior to this
commit was running without limit, meaning when a lot of messages have to be transmitted dlt-daemon might
be killed by systemd watchdog due to being busy
with sending and not updating the watchdog anymore. This commit introduces a timeout in dlt_daemon_process_user_message_log which allows this function to run at most watchdog_trigger_interval seconds.
This MR extends the logic introduced in https://github.com/COVESA/dlt-daemon/pull/595 as the original commit still allowed systemd to kill dlt-daemon
To test we need the following things
* dlt-daemon started via systemd with enabled watchdog
* a lot of logging going into the daemon
Excecute the script below on your test system.
It spawns a lot of dlt-receive proceses, the goal is for …

watchdog: fix another possible watchdog timeout

---

src/daemon/dlt-daemon.c

If parsing of config file fails, close the file before returning an error.

Close config file handle on error.

---

doc/dlt-system.conf.5.md
src/system/dlt-system-journal.c
src/system/dlt-system-options.c
src/system/dlt-system.conf
src/system/dlt-system.h

Add a new JournalUseUptimeOnly config toggle. With this toggle you can supress date and time from the dlt-system payload, so we show only the uptime of the system.
This toggle is for data protection purposes.
<sub>Daniel Weber, [daniel.w.weber@mercedes-benz.com](mailto:daniel.w.weber@mercedes-benz.com), Mercedes-Benz Tech Innovation GmbH, [imprint](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)</sub>

dlt-system: add config to use uptime only

---

src/dlt-qnx-system/dlt-qnx-slogger2-adapter.cpp

- Discard messages after timeout
- Log warning message only once until a new slog message was logged
successful
Signed-off-by: Michael Methner <michael.methner@de.bosch.com>

Fix timeout handling for slog messages

---

src/shared/dlt_common.c

Fixes [https://github.com/COVESA/dlt-daemon/security/code-scanning/23](https://github.com/COVESA/dlt-daemon/security/code-scanning/23)
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Fix code scanning alert #23: Incorrect return-value check for a 'scanf'-like function

---

src/shared/dlt_common.c

Some serial definitions is not valid in Linux Spac

Fixing failed build for dlt-daemon in Linux Sparc

---

src/lib/dlt_user.c

The original place of mutex lock was wrong because it didn't protect dlt_housekeeper_running
and there was no mutex lock when sending signal.

Edited mutex lock of dlt_housekeeper_running_mutex

---

src/lib/dlt_user.c

Current implementation just accumulated 500,000,000.
The glibc NPTL pthread_cond_timedwait() implementation return EINVAL if It's  range is not in 0 ~  1,000,000,000..
Here is `pthread_cond_timedwait()` implementation of glibc master branch.
https://github.com/bminor/glibc/blob/9d4b4515a88c5d0bbfc7809374f322c507c2d779/nptl/pthread_cond_wait.c#L633-L636
It calls `valid_nanoseconds()`.
https://github.com/bminor/glibc/blob/9d4b4515a88c5d0bbfc7809374f322c507c2d779/include/time.h#L516-L520
So it makes lots of pthread_cond_timedwait() call with mutex acquire & release when ts.tv_nsec is over 500,000,000.
This commit set proper value for appending 500ms.

dlt-user: fix timeout value of pthread_cond_timedwait() for waiting housekeeper initialization

---

src/lib/dlt_user.c
tests/gtest_dlt_user.cpp

* improve free after failures in init
* check if freeing in some methods
* add missing free in unit tests
This fixed #522 on my machines but your that's not the main purpose of this PR. Therefore before resolving #522 more testing is required.
1. Fixes the following address sanitizer issue
```
exiting
#0 0x7ffff7625fc6 in __interceptor_sigaltstack ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:9986
#1 0x7ffff768c493 in __asan::PlatformUnpoisonStacks() ../../../../src/libsanitizer/asan/asan_posix.cpp:44
#2 0x7ffff769202c in __asan_handle_no_return ../../../../src/libsanitizer/asan/asan_rtl.cpp:612
#4 0x7ffff7073ac2 in start_thread nptl/pthread_create.c:442
#5 0x7ffff710584f  (/lib/x86_64-linux-gnu/libc.so.6+0x12684f)
at offset 160 in frame
This frame has 2 …
```

dlt-user: fix memory issues

---

src/daemon/dlt-daemon.c

Fix signedness of some variables so the compiler flags sign-compare and pointer-sign can be enabled.
This doesn't change any behaviour nor fix any bugs. It is just to be able to run the compiler with those flags so future bugs can be avoided.

Fix compiler warnings related to signs

---

src/offlinelogstorage/dlt_offline_logstorage_behavior.c

Adds check in dlt_logstorage_sync_to_file that gzlog is NULL if the dlt-daemon is compiled with gzip, otherwise that statement will always return true if using gzip-compression on logs.

Check gzlog in dlt_logstorage_sync_to_file

---

src/offlinelogstorage/dlt_offline_logstorage_behavior.c

dlt_logstorage_log_file_name assumed the suffix always is .dlt which is not be the case if gzip compression is enabled. Changed to assume .dlt.gz when smax is calculated as it prevents buffer overflow if filenames are long and gzip is enabled.

Fix file length calculation

---

src/offlinelogstorage/dlt_offline_logstorage.c
src/offlinelogstorage/dlt_offline_logstorage.h
src/offlinelogstorage/dlt_offline_logstorage_behavior.c

If dlt_daemon is compiled with gzip compression any use of GzipCompression will turn it on. This is due to incorrect check of the flag where it is checked as if it was a boolenan when it is an int where only the value DLT_LOGSTORAGE_GZIP_ON means that it should be enabled.

Fix usage of gzip_compression

---

src/daemon/dlt_daemon_offline_logstorage.c

make sure the warning about disable network is only sent if disable network flag is set and only send the warning once instead of for every message.

Remove DisableNetwork logspam

---

include/dlt/dlt_user.h.in
src/lib/dlt_user.c

Since glibc 2.25, getpid() no longer caches the PID, instead performing a full syscall every time. This means we're performing a full syscall roundtrip for *every* *single* *log* *message* on the system.
This patch caches the result of getpid() when appropriate, avoiding unnessicary syscalls.

dlt-system: Avoid expensive getpid() syscalls

---

include/dlt/dlt_user.h.in

This mutex type allow checking on recursive locking, unlock without lock hold, double unlock. Hence add the checking in MACRO.
+-------------------------------------------+-------------+
| Scenario                                                  | ERRNO         |
+---------------+-------------------------------+---------+
| Same thread   | Lock twice - recursive lock | EDEADLK  |
|                        | Unlock without holding lock | EPERM   |
+---------------+-----------------------------+-----------+
| Multithread    | Unlock without holding lock | EPERM   |
+---------------+-----------------------------+-----------+

lib: dlt thread-safe with mutex errorcheck

---

src/dlt-qnx-system/dlt-qnx-slogger2-adapter.cpp

Problem: Thread not starting on QNX 8.0
Cause: pthread_create() was failing due to an uninitialized pthread_attr_t structure.
Fix:
- Properly initialize "pthread_attr_t" using pthread_attr_init()
- Add error handling and logging for pthread_create failures.

Fix thread initialization for QNX and handle pthread_create return value

---

src/console/dlt-control-common.c

Socket is shutdown and closed before that, so thread will complete its task, here is the listening task, so calling pthread_cancel does not need here

Remove pthread_cancel

---

src/daemon/dlt-daemon.c

This reverts commit 1737de27825c691e925a7d42abe34311159c48c6.
The original commit aimed to address potential partial message reception. However, this issue is not observed on Linux and QNX systems, which are the primary target platforms for dlt-daemon. Furthermore, the changes introduced by the reverted commit have been found to cause message loss in certain scenarios.
Therefore, to ensure the stability and reliability of dlt-daemon, this commit reverts the problematic changes.
This revert addresses issue #631.

Revert "dlt-daemon: Handle partial message parsing in receiver buffer"

---

Android.bp
CMakeLists.txt
src/daemon/dlt_daemon_common.c
src/shared/dlt_user_shared.c

Problem: dlt-daemon occasionally freezes on QNX when client processes exit unexpectedly
Cause: Socket errors return EBADF but only EPIPE is handled, and select() blocks indefinitely despite timeout (likely a QNX-specific issue)
Fix:
* Add EBADF error handling alongside EPIPE to properly close invalid sockets
* Replace select() with poll() for improved timeout handling efficiency in log output functions

Fix occasional dlt-daemon hanging when client process exits on QNX

---

README.md
ReleaseNotes.md
doc/dlt-system.conf.5.md
doc/dlt_design_specification.md
doc/dlt_for_developers.md

Fixed Fix spelling errors in the documentation using the agent.

Fix spelling errors in the documentation 
