COVESA/dlt-daemon

src/kpi/dlt-kpi-common.c
src/kpi/dlt-kpi-interrupt.c
src/kpi/dlt-kpi-options.c
src/kpi/dlt-kpi-process-list.c
src/kpi/dlt-kpi-process.c
src/kpi/dlt-kpi.c

Added null pointer checking
Added input parameter checking
Added return values in non-void functions
Added proper error message for debugging purpose
Signed-off-by: amberbhardwaj <amber.bhardwaj10@gmail.com>

Input parameter check & Error message modification

---

doc/dlt_book.txt
doc/dlt_loglevel_explained.txt

Signed-off-by: Lutz Helwing <lutz_helwing@mentor.com>

Add short explanation for DLT log level

---

src/daemon/dlt_daemon_socket.c

Since these logging changes helped me troubleshoot my DLT config, I would like to submit them in the hope that they will help others.
Related (closed) issue:
https://github.com/GENIVI/dlt-daemon/issues/40

improve error reporting in dlt_daemon_socket

---

src/shared/dlt_config_file_parser.c
src/shared/dlt_config_file_parser.h

This PR Replaces hash functions with list in config file parser

file parser: Replace hash functions with list

---

src/daemon/dlt-daemon.c
src/daemon/dlt_daemon_client.c
src/daemon/dlt_daemon_common.c
src/daemon/dlt_daemon_common.h
src/daemon/dlt_daemon_offline_logstorage.c
src/lib/dlt_client.c
tests/gtest_dlt_daemon_common.cpp
tests/gtest_dlt_daemon_gateway.cpp

Prepare daemon to store applications/context information of other ECUs as well
Signed-off-by: ManikandanC <Manikandan.Chockalingam@in.bosch.com>

dlt-daemon: per ECU list of user information

---

include/dlt/dlt_common.h
src/daemon/dlt_daemon_connection.c
src/daemon/dlt_daemon_event_handler.c
src/daemon/dlt_daemon_offline_logstorage.c
src/gateway/dlt_gateway.c
src/lib/dlt_client.c
src/offlinelogstorage/dlt_offline_logstorage.c
src/offlinelogstorage/dlt_offline_logstorage_behavior.c

Static to dlt static

---

.travis.yml
tests/CMakeLists.txt

Adding options and package dependencies to Travis CI build including the systemd support

Travis CI: build with systemd enabled

---

README.md
doc/CMakeLists.txt
doc/dlt_book.txt
doc/dlt_cdh.md
doc/dlt_extended_network_trace.md
doc/dlt_filetransfer.md
doc/dlt_for_developers.md
doc/dlt_kpi.md
doc/dlt_user_manual.txt

#[Signed-off-by:] thanhbnq <thanh.buinguyenquoc@vn.bosch.vn>

doc: Update doc/CMakeList.txt after cleanup documentation (#111)

---

src/lib/dlt_user.c

Sometimes it happens that internal threads present
in DLT library are cancelled with one of the task
still holding the mutex, then the main task gets locked forever.
The following changes have been made:
- Cleanup on thread cancellation with pthread_cleanup_push() is
introduced
- Locking on the message queue lock and subsequent signaling in
dlt_stop_threads is only done if the segmented thread was created.
- It is unnecessary to have a robust mutex for the message queue.
Replace it with a normal mutex and remove EOWNERDEAD logic. Add a
pthread_cancel handler to the segmented thread that might hold the
message queue mutex.
- Message queue mutex is statically initialized
Signed-off-by: S. Hameed <shameed@jp.adit-jv.com>
Signed-off-by: Jeevan Ramakant Nagvekar <jeevan.nagvekar1@wipro.com> …

Unlock buffer on termination

---

.travis.yml
.travis/gtest_dlt_all.sh

To do more testing on Travis CI, a script is added to run all unit
tests which exists under tests directory.

Travis CI: Run unit test

---

src/lib/dlt_user.c

For "POSIX: Replace usleep with nanosleep" as [ReleaseNotes.md](https://github.com/GENIVI/dlt-daemon/blob/master/ReleaseNotes.md#2183)

dlt_user: use posix nanosleep

---

src/console/dlt-control-common.c
src/daemon/dlt_daemon_client.c
src/daemon/dlt_daemon_event_handler.c
src/lib/dlt_env_ll.c
src/lib/dlt_user.c
src/offlinelogstorage/dlt_offline_logstorage.c
src/shared/dlt_config_file_parser.c
src/tests/dlt-test-stress-user.c

Fix the findings from static analysis.
Related commit: 5c8f88d logstorage: fix compile error

Correct sa findings

---

include/dlt/dlt_common.h
include/dlt/dlt_shm.h
src/daemon/dlt-daemon.c
src/daemon/dlt-daemon.h
src/lib/dlt_user.c
src/shared/dlt_common.c
src/shared/dlt_shm.c
tests/CMakeLists.txt
tests/gtest_dlt_daemon_gateway.sh
tests/gtest_dlt_shm.cpp

Replaced all Linux specific shared memory APIs with POSIX alternatives.

using POSIX shared memory APIs (#90)

---

CMakeLists.txt
README.md
doc/dlt.conf.5.md
src/daemon/CMakeLists.txt
src/daemon/dlt-daemon.c
src/daemon/dlt-daemon.h
src/daemon/dlt.conf
src/daemon/dlt_daemon_client.c
src/daemon/dlt_daemon_common.h
src/daemon/udp_connection/dlt_daemon_udp_common_socket.h
src/daemon/udp_connection/dlt_daemon_udp_socket.c
src/daemon/udp_connection/dlt_daemon_udp_socket.h
src/examples/CMakeLists.txt
src/examples/dlt-example-multicast-clientmsg-view.c

Signed-off-by: sunil.s <sunil.s@lge.com>

UDP Multicast implementation

---

src/daemon/dlt-daemon.c
src/daemon/udp_connection/dlt_daemon_udp_common_socket.h
src/daemon/udp_connection/dlt_daemon_udp_socket.c
src/daemon/udp_connection/dlt_daemon_udp_socket.h

1. Removed unused headers(epoll) in UDP connection
2. Added socket close

Removed unused headers(epoll) in UDP connection

---

src/shared/dlt_common.c

This commit is fixed the memory leak in case the dlt application do
reattach to the daemon.

libdlt: fix memory leak

---

doc/dlt_for_developers.md
include/dlt/dlt_user.h
include/dlt/dlt_user_macros.h
src/lib/dlt_user.c

Provide GET_APPID macro (#187)

---

src/console/logstorage/dlt-logstorage-list.c
src/daemon/dlt-daemon.c
src/daemon/dlt_daemon_socket.c
src/lib/dlt_user.c

For fixing  resource leak and unint  warning by coverity

fix some warnings from coverity scan

---

include/dlt/dlt_user.h
src/console/logstorage/dlt-logstorage-ctrl.c
src/daemon/dlt_daemon_event_handler.c
src/daemon/dlt_daemon_event_handler.h
src/daemon/dlt_daemon_event_handler_types.h
src/lib/dlt_user.c
src/tests/dlt-test-init-free.c

this fix a bunch of failures due to gcc hardening flags + musl libc implementation

Fix build musl

---

src/offlinelogstorage/dlt_offline_logstorage.h

Revert "dlt_offline: fix build failures with gcc-10"

---

doc/dlt_for_developers.md
include/dlt/dlt_common.h
include/dlt/dlt_user.h.in
include/dlt/dlt_user_macros.h
src/lib/dlt_user.c
src/shared/dlt_common.c
tests/gtest_dlt_user.cpp

Add "name" and "unit" attributes (i.e. VARI contents) in verbose mode.

Add verbose mode attribute handling

---

README.md

Contact information update

---

src/lib/dlt_user.c

Fix wrong type used for function return value

fix bad funcion cast in dlt_user_log_out_error_handling

---

doc/dlt_for_developers.md
include/dlt/dlt_user.h.in
src/lib/dlt_user.c
tests/gtest_dlt_user.cpp

@ssugiura, another PR for consideration, please have a look.

Make nonverbose mode non exclusive

---

doc/dlt_for_developers.md
include/dlt/dlt_user.h.in
include/dlt/dlt_user_macros.h
src/lib/dlt_user.c
tests/gtest_dlt_user.cpp

For some reasons, some of the user functions were missing.

Add missing string functions

---

CMakeLists.txt
ReleaseNotes.md

Update ReleaseNotes and version to v2.18.7

---

src/console/dlt-convert.c
src/console/dlt-sortbytimestamp.c

Hello,
#313 Commit error, I send a new one.
I have taken into account your requirements.
Thanks.

 Code refactoring: remove duplicate conditionals

---

CMakeLists.txt
doc/dlt_build_options.md

cmake: Set WITH_LEGACY_INCLUDE_PATH to ON as default

---

CMakeLists.txt
ReleaseNotes.md

Update ReleaseNotes and version to v2.18.8

---

src/lib/dlt_filetransfer.c

filetransfer: Return error if no free space

---

src/lib/dlt_user.c

lib: Correct VARI usage in dlt_user_log_write_uint

---

tests/CMakeLists.txt
tests/gtest_dlt_daemon_gateway.cpp

tests: Deplicate unused files and variables

---

doc/dlt_for_developers.md

Closes #365
Signed-off-by: Martin Willers <M.Willers@gmx.net>

Fix the target name in documentation

---

README.md

Set link to github actions in COVESA/dlt-daemon.

README: Update link to github actions

---

src/lib/dlt_client.c

Connect TCP socket with non-blocking socket
Check errno and getsockopt to guarantee that the socket connection is established successfully
Signed-off-by: Le Tin <tin.le@vn.bosch.com>

dlt_client:Block in connect()

---

src/console/dlt-receive.c
src/lib/dlt_client.c

This PR is working as revised version of #400 .
- Keep the committer name and email.
- Improve coding style

dlt-receive: set host interface and allow multiple udp multicast addresses

---

src/shared/dlt_common.c

Check for negative index in dlt_file_message

---

src/adaptor/CMakeLists.txt

This should fix problem in #448

This changes a mispatch from fcb676a7 to install udp binary correctly

---

src/lib/dlt_user.c

in case the house keeper thread does not start
we should not wait indefinitely but abort
the wait after a 10s

house-keeper: remove infinite wait

---

README.md

Removed deprecated LGTM, added CodeQL

Update status badges on README.md

---

CMakeLists.txt

Signed-off-by: LUU QUANG MINH <Minh.LuuQuang@vn.bosch.com>

gtest: Update pointer to v1.13.0

---

src/daemon/CMakeLists.txt
src/lib/CMakeLists.txt

Add additional "MSYS" checking for CMAKE_SYSTEM_NAME to support compilation under MSYS2.

Added compilation support under MSYS2

---

src/console/dlt-receive.c

Remove extra file number increment in name

---

src/lib/dlt_client.c

Avoid heap-buffer-overflow in dlt_client_connect

---

systemd/dlt-dbus.service.cmake
systemd/dlt-system.service.cmake
systemd/dlt.service.cmake

+ Remove unusual relationship and replace with multi-user
+ Avoid dlt conflict on shutdown when applying no dependency
See https://github.com/COVESA/dlt-daemon/pull/574

systemd: correct service files relationship

---

src/console/dlt-receive.c

+ Correct the waiting loop
+ Replace poll(NULL) with sleep()
+ Correct mispelling

dlt-receive: rework reconnect option for PR620

---

include/dlt/dlt_log.h
src/shared/dlt_log.c

dlt_log_init function should return with value

Fix return value of dlt_log_init function

---

doc/dlt_for_developers.md

Fix small typo and fix function call in example code in docs
